name: projekt_erster_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/rahmen1.png
    - lib/assets/images/hintergrund.jpg
    - lib/assets/images/famka-logo.png
    - lib/assets/images/test_button.jpg